package com.starlc.test;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static org.junit.Assert.assertNotNull;

import org.junit.Test;

import com.starlc.common.App;

/**
 * xx
 *
 * @author xx
 * @since jdk1.6
 * @version 2017年11月30日 xx
 */
public class AppTest {
    
    /**
     * xx
     */
    @Test
    public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
